version: "3.8"
services:
  db:
    container_name: my-postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgre:/var/lib/postgresql/data
    networks:
      - dev
  pgadmin:
    container_name: dpage/pgadmin4

networks:
  default:
    external:
      name: dev

